### ISSUE TITLE
ADR on current match stats

### ISSUE THREAD

**Issue by Trox91** [Dietze1595/Faceitplugin#19]
Hi Marcel,

I was wondering if there is a current way to add the ADR to the current match stats?

would be an great feature 

Best

**Comment by SkyuzMe** [comment]
@Trox91 Could you please help me? i do all that was describe for instalation but nothing work. i dont see some information to be displayed

**Comment by Dietze1595** [comment]
Sry, i was on holidays. Still an Issue? I think it will be overload the Overlay of the matchstats - if there will be a column with ADR. What do you think?
