### ISSUE TITLE
does not fit the resoulution in obs

### ISSUE THREAD

**Issue by SkyuzMe** [Dietze1595/Faceitplugin#21]
I tested on 1920x1080 and 1280x960 but the circle in obs does not fit exact the resolution. is lesser then cs2 radar

**Comment by Trox91** [comment]
If u playing 4:3 but got it stretched to 16:9 in OBS. Use 4:3 and rescale it in OBS. Working fine for me. Just a bit work and should be done within minutes. 

If ingame 16:9 and OBS 16:9 - just rescale the browser source in obs until it fits.

**Comment by SkyuzMe** [comment]
> If u playing 4:3 but got it stretched to 16:9 in OBS. Use 4:3 and rescale it in OBS. Working fine for me. Just a bit work and should be done within minutes.
> 
> If ingame 16:9 and OBS 16:9 - just rescale the browser source in obs until it fits.

Can you share the exact size from obs to be fited?

**Comment by Trox91** [comment]
![image](https://github.com/user-attachments/assets/07d73a72-90d9-4b7d-a133-4b233a4ff818)

I don’t have exact w/h size for you. I just rescaled it in preview window. oBS is not showing the exact size

**Comment by SkyuzMe** [comment]
Click right click transform and first option from popup menu (E) and will see the exact size

**Comment by SkyuzMe** [comment]
Ок

**Comment by Dietze1595** [comment]
will check the resolution and will come back to you to test.
