### ISSUE TITLE
Could you please make this?

### ISSUE THREAD

**Issue by SkyuzMe** [Dietze1595/Faceitplugin#26]
Could tou please make something like this ?
![IMG_1334](https://github.com/user-attachments/assets/71cc1669-e960-4ecd-849f-d03faa2aba9f)

statistics about fcaeit games for obs?

**Comment by SkyuzMe** [comment]
![IMG_1334](https://github.com/user-attachments/assets/d964c21e-e0e8-4f53-b238-ca4bd3bcc72b)

**Comment by SkyuzMe** [comment]
![Uploading IMG_1334.png…]()

**Comment by Dietze1595** [comment]
No, its a radar overlay, nothing else
