### ISSUE TITLE
Cs2

### ISSUE THREAD

**Issue by bijkomune** [Dietze1595/Faceitplugin#8]
Can you update to cs2?

**Comment by Dietze1595** [comment]
I can try, I haven't had time to look at it yet because I haven't played CS
since 2021.

bijkomune ***@***.***> schrieb am Mi., 4. Okt. 2023, 15:27:

**Comment by Dietze1595** [comment]
Just paste the file gamestate_integration_overlay.cfg in the new cs folder for cs2

`\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg`

**Comment by Dietze1595** [comment]
Fixed
